services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb+srv://mrigank:aQ96oxxGH8VSvZPQ@cluster0.qe2rcoy.mongodb.net/
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
